server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /admin {
        try_files $uri /admin.html;
    }

    location /admin-panel {
        try_files $uri /admin-panel.html;
    }

    # Блокируем прямой доступ к .html
    location ~ \.html$ {
        internal;
    }

    # Разрешаем статику
    location ~* \.(css|js|png|jpg)$ {
        expires 30d;
        access_log off;
    }
}
